/* -*- mode: c++; c-basic-offset: 4; tab-width: 4; indent-tabs-mode: t -*- */

/* 
 * PropertyInit.cpp 
 *
 * This file is part of the Chemical Data Processing Toolkit
 *
 * Copyright (C) 2003-2010 Thomas A. Seidel <thomas.seidel@univie.ac.at>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either  
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; see the file COPYING. If not, write to
 * the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */


#include "StaticInit.hpp"

#include "CDPL/Chem/ReactionProperty.hpp"
#include "CDPL/Chem/MoleculeProperty.hpp"
#include "CDPL/Chem/AtomProperty.hpp"
#include "CDPL/Chem/BondProperty.hpp"
#include "CDPL/Chem/MolecularGraphProperty.hpp"
#include "CDPL/Base/ValueKeyDefinition.hpp"


namespace CDPL 
{

	namespace Chem
	{

		// Reaction property-keys

		namespace ReactionProperty
		{

			CDPL_DEFINE_VALUE_KEY(NAME);

			CDPL_DEFINE_VALUE_KEY(MATCH_EXPRESSION);
			CDPL_DEFINE_VALUE_KEY(MATCH_CONSTRAINTS);
			CDPL_DEFINE_VALUE_KEY(COMPONENT_GROUPS);
			CDPL_DEFINE_VALUE_KEY(ATOM_MAPPING);

			CDPL_DEFINE_VALUE_KEY(MDL_USER_INITIALS);
			CDPL_DEFINE_VALUE_KEY(MDL_PROGRAM_NAME);
			CDPL_DEFINE_VALUE_KEY(MDL_TIMESTAMP);
			CDPL_DEFINE_VALUE_KEY(MDL_REGISTRY_NUMBER);
			CDPL_DEFINE_VALUE_KEY(MDL_COMMENT);
			CDPL_DEFINE_VALUE_KEY(MDL_REACTION_DATA);
			CDPL_DEFINE_VALUE_KEY(MDL_MOLECULE_RECORD);
			CDPL_DEFINE_VALUE_KEY(MDL_INTERNAL_REGISTRY_NUMBER);
			CDPL_DEFINE_VALUE_KEY(MDL_EXTERNAL_REGISTRY_NUMBER);
			CDPL_DEFINE_VALUE_KEY(MDL_RXN_FILE_VERSION);
		}

		// MolecularGraph property-keys

		namespace MolecularGraphProperty
		{

			CDPL_DEFINE_VALUE_KEY(NAME); 
		}

		// Molecule property-keys

		namespace MoleculeProperty
		{

			CDPL_DEFINE_VALUE_KEY(MATCH_CONSTRAINTS);
			CDPL_DEFINE_VALUE_KEY(MATCH_EXPRESSION);
			
			CDPL_DEFINE_VALUE_KEY(RINGS);
			CDPL_DEFINE_VALUE_KEY(AROMATIC_RINGS);
			CDPL_DEFINE_VALUE_KEY(SSSR);
			CDPL_DEFINE_VALUE_KEY(AROMATIC_ATOMS_AND_BONDS);
			CDPL_DEFINE_VALUE_KEY(RING_ATOMS_AND_BONDS);
	
			CDPL_DEFINE_VALUE_KEY(COMPONENTS);
			CDPL_DEFINE_VALUE_KEY(COMPONENT_GROUPS);

			CDPL_DEFINE_VALUE_KEY(STOICHIOMETRIC_NUMBER);

			CDPL_DEFINE_VALUE_KEY(TOPOLOGICAL_DISTANCE_MATRIX);
			CDPL_DEFINE_VALUE_KEY(GEOMETRICAL_DISTANCE_MATRIX);
		
			CDPL_DEFINE_VALUE_KEY(MDL_USER_INITIALS);
			CDPL_DEFINE_VALUE_KEY(MDL_PROGRAM_NAME);
			CDPL_DEFINE_VALUE_KEY(MDL_TIMESTAMP);
			CDPL_DEFINE_VALUE_KEY(MDL_DIMENSIONALITY);
			CDPL_DEFINE_VALUE_KEY(MDL_SCALING_FACTOR1);
			CDPL_DEFINE_VALUE_KEY(MDL_SCALING_FACTOR2);
			CDPL_DEFINE_VALUE_KEY(MDL_ENERGY);
			CDPL_DEFINE_VALUE_KEY(MDL_REGISTRY_NUMBER);
			CDPL_DEFINE_VALUE_KEY(MDL_COMMENT);
			CDPL_DEFINE_VALUE_KEY(MDL_CHIRAL_FLAG);
			CDPL_DEFINE_VALUE_KEY(MDL_CTAB_VERSION);
			CDPL_DEFINE_VALUE_KEY(MDL_STRUCTURE_DATA);
		}

		// Atom property-keys

		namespace AtomProperty
		{

			CDPL_DEFINE_VALUE_KEY(NAME);
			CDPL_DEFINE_VALUE_KEY(SYMBOL);
			CDPL_DEFINE_VALUE_KEY(TYPE);

			CDPL_DEFINE_VALUE_KEY(FORMAL_CHARGE);
			CDPL_DEFINE_VALUE_KEY(ISOTOPE);
			CDPL_DEFINE_VALUE_KEY(RADICAL_TYPE);
			CDPL_DEFINE_VALUE_KEY(HYBRIDIZATION); 

			CDPL_DEFINE_VALUE_KEY(RING_FLAG);
			CDPL_DEFINE_VALUE_KEY(AROMATICITY_FLAG);

			CDPL_DEFINE_VALUE_KEY(UNPAIRED_ELECTRON_COUNT);
		
			CDPL_DEFINE_VALUE_KEY(IMPLICIT_HYDROGEN_COUNT);
	
			CDPL_DEFINE_VALUE_KEY(COORDINATES_2D);
			CDPL_DEFINE_VALUE_KEY(COORDINATES_3D);
		
			CDPL_DEFINE_VALUE_KEY(MORGAN_NUMBER);
			CDPL_DEFINE_VALUE_KEY(CANONICAL_NUMBER);
			CDPL_DEFINE_VALUE_KEY(CIP_PRIORITY);
			CDPL_DEFINE_VALUE_KEY(SYMMETRY_CLASS);

			CDPL_DEFINE_VALUE_KEY(STEREO_DESCRIPTOR);
			CDPL_DEFINE_VALUE_KEY(STEREO_CENTER_FLAG);
			CDPL_DEFINE_VALUE_KEY(CIP_CONFIGURATION);
			CDPL_DEFINE_VALUE_KEY(MDL_PARITY);
			CDPL_DEFINE_VALUE_KEY(MDL_DB_STEREO_CARE_FLAG);

			CDPL_DEFINE_VALUE_KEY(PEOE_CHARGE);
		
			CDPL_DEFINE_VALUE_KEY(REACTION_CENTER_STATUS);
			CDPL_DEFINE_VALUE_KEY(REACTION_ATOM_MAPPING_ID);
			
			CDPL_DEFINE_VALUE_KEY(MATCH_CONSTRAINTS);
			CDPL_DEFINE_VALUE_KEY(MATCH_EXPRESSION);
			CDPL_DEFINE_VALUE_KEY(MATCH_EXPRESSION_STRING);
		
			CDPL_DEFINE_VALUE_KEY(COMPONENT_GROUP_ID);
		}

		// Bond property-keys

		namespace BondProperty
		{

			CDPL_DEFINE_VALUE_KEY(ORDER);

			CDPL_DEFINE_VALUE_KEY(RING_FLAG);
			CDPL_DEFINE_VALUE_KEY(AROMATICITY_FLAG);
		
			CDPL_DEFINE_VALUE_KEY(STEREO_DESCRIPTOR);
			CDPL_DEFINE_VALUE_KEY(STEREO_CENTER_FLAG);
			CDPL_DEFINE_VALUE_KEY(CIP_CONFIGURATION);
			CDPL_DEFINE_VALUE_KEY(STEREO_2D_FLAG);
			CDPL_DEFINE_VALUE_KEY(DIRECTION);

			CDPL_DEFINE_VALUE_KEY(REACTION_CENTER_STATUS);

			CDPL_DEFINE_VALUE_KEY(MATCH_CONSTRAINTS);
			CDPL_DEFINE_VALUE_KEY(MATCH_EXPRESSION);
			CDPL_DEFINE_VALUE_KEY(MATCH_EXPRESSION_STRING);
		}

		void initProperties() {}
	}
}
