set(_CXX11_TEST_PROG_DIR ${CMAKE_CURRENT_LIST_DIR} CACHE INTERNAL "")

MACRO(CHECK_CXX11_SUPPORT SUPPORTED)
  SET(${SUPPORTED} FALSE)

  TRY_RUN(_RUN_RESULT _COMPILE_RESULT ${CMAKE_CURRENT_BINARY_DIR} "${_CXX11_TEST_PROG_DIR}/CXX11Test.cpp") 

  IF(_COMPILE_RESULT AND _RUN_RESULT EQUAL 0)
    SET(${SUPPORTED} TRUE)
  ENDIF(_COMPILE_RESULT AND _RUN_RESULT EQUAL 0)
ENDMACRO(CHECK_CXX11_SUPPORT)
